version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: playwithllm-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: playwithllm-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local
